MarketPlace/ViewModels/UserViewModel.cs
using MarketPlace.Models;
using Microsoft.AspNetCore.Identity;

namespace MarketPlace.ViewModels;

public class UserViewModel
{
    public ApplicationUsers ApplicationUsers { get; set; }
    public string Role { get; set; }
}

MarketPlace/Controllers/OrderController.cs
using MarketPlace.Data;
using MarketPlace.Helpers;
using MarketPlace.Interfaces;
using MarketPlace.Models;
using MarketPlace.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace MarketPlace.Controllers;
public class OrderController : Controller
{
    private readonly IOrderRepository _orderRepository;
    private readonly IHttpContextAccessor _httpContextAccessor;

    public OrderController(IOrderRepository orderRepository, IHttpContextAccessor httpContextAccessor)
    {
        _orderRepository = orderRepository;
        _httpContextAccessor = httpContextAccessor;
    }

    public async Task<IActionResult> ViewOrder()
    {
        var userId = _httpContextAccessor.HttpContext.User.GetUserId();
        var userOrders = await _orderRepository.GetUserOrdersAsync(userId);
        return View(userOrders);
    }

    public async Task<IActionResult> GetOrdersFromVendor()
    {
        var vendorId = _httpContextAccessor.HttpContext.User.GetUserId();
        var orders = await _orderRepository.GetOrdersFromVendorAsync(vendorId);
        return View(orders);
    }
    [HttpPost]
    public async Task<IActionResult> EditOrder(Orders model)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }
        await _orderRepository.EditOrderFromVendorAsync(model);
        return RedirectToAction("GetOrdersFromVendor");
    }
}

MarketPlace/Controllers/UserController.cs
using MarketPlace.Data;
using MarketPlace.Helpers;
using MarketPlace.Interfaces;
using MarketPlace.Models;
using MarketPlace.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static MarketPlace.Helpers.Roles;

namespace MarketPlace.Controllers;
public class UserController : Controller
{
    private readonly IUserRepository _userRepository;
    private readonly IHttpContextAccessor _httpContextAccessor;
    private readonly UserManager<ApplicationUsers> _userManager;
    private readonly SignInManager<ApplicationUsers> _signInManager;

    public UserController(IUserRepository userRepository, IHttpContextAccessor httpContextAccessor,
        UserManager<ApplicationUsers> userManager, SignInManager<ApplicationUsers> signInManager)
    {
        _userRepository = userRepository;
        _httpContextAccessor = httpContextAccessor;
        _userManager = userManager;
        _signInManager = signInManager;
    }
    public async Task<IActionResult> MyProfile()
    {
        var userId = _httpContextAccessor.HttpContext.User.GetUserId();
        var user = await _userRepository.GetUserByIdAsync(userId);

        var roles = await _userManager.GetRolesAsync(user);

        var model = new UserViewModel()
        {
            ApplicationUsers = user,
            Role = roles.FirstOrDefault()
        };
        return View(model);
    }
    public async Task<IActionResult> EditProfile()
    {
        var userId = _httpContextAccessor.HttpContext.User.GetUserId();
        var user = await _userRepository.GetUserByIdAsync(userId);

        return View(user);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditProfile(ApplicationUsers model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var userId = _httpContextAccessor.HttpContext.User.GetUserId();
        var user = await _userRepository.GetUserByIdNoTracking(userId);

        user.FirstName = model.FirstName;
        user.LastName = model.LastName;
        user.Email = model.Email;
        user.PhoneNumber = model.PhoneNumber;
        user.UserName = model.UserName;

        await _userRepository.UpdateProfileAsync(user);
        return RedirectToAction("MyProfile");
    }
    public async Task<IActionResult> AddAddress()
    {
        var address = new Addresses();
        return View(address);
    }
    [HttpPost]
    public async Task<IActionResult> AddAddress(Addresses model)
    {
        
        await _userRepository.AddAddressAsync(model);

        var userId = _httpContextAccessor.HttpContext.User.GetUserId();
        var user = await _userRepository.GetUserByIdAsync(userId);
        user.Address = model;
        await _userManager.UpdateAsync(user);
        return RedirectToAction("MyProfile");
    }
    public async Task<IActionResult> ChangeAddress()
    {
        var userId = _httpContextAccessor.HttpContext.User.GetUserId();
        var user = await _userRepository.GetUserByIdNoTracking(userId);
        var address = user.Address;
        return View(address);
    }
    [HttpPost]
    public async Task<IActionResult> ChangeAddress(Addresses model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        var userId = _httpContextAccessor.HttpContext.User.GetUserId();
        var user = await _userRepository.GetUserByIdAsync(userId);

        user.Address.Country = model.Country;
        user.Address.City = model.City;
        user.Address.Street = model.Street;
        user.Address.PostalCode = model.PostalCode;
        await _userManager.UpdateAsync(user);
        return RedirectToAction("MyProfile");
    }
    [HttpPost]
    public async Task<IActionResult> BecomeVendor()
    {
        var userId = _httpContextAccessor.HttpContext.User.GetUserId();
        var user = await _userRepository.GetUserByIdAsync(userId);
        if (user.Address is null)
        {
            TempData["NoAddress"] = "You must add your address first!";
            return RedirectToAction("AddAddress");
        }

        if (!user.EmailConfirmed)
        {
            TempData["NotConfirmed"] = "You must verify your email to become vendor!";
            return RedirectToAction("MyProfile");
        }
        await _userManager.AddToRoleAsync(user, Role.Vendor);
        await _userManager.RemoveFromRoleAsync(user, Role.User);
        await _userRepository.SaveAsync();
        await _signInManager.RefreshSignInAsync(user);
        return RedirectToAction("MyProfile");
    }
}

MarketPlace/Views/User/AddAddress.cshtml
@model Addresses

<body>
    <div class="container">
        <div class="py-5 text-center">
            <img class="d-block mx-auto mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
            <h2>Address form</h2>
            <label style="font-size:30px;text-align:center;display:block" class="text-danger">@TempData["NoAddress"]</label>
        </div>
        <form method="post" asp-action="AddAddress">
            <div class="row BtnCenter">
                <div class="col-md-8 order-md-1">
                    <h4 class="mb-3">Billing address</h4>
                    <div class="mb-3">
                        <label asp-for=Country></label>
                        <input asp-for=Country type="text" class="form-control" placeholder="Ukraine" required>
                        <div class="invalid-feedback">
                            Please enter your country.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label asp-for=City></label>
                        <input asp-for=City type="text" class="form-control" placeholder="Kyiv">
                    </div>

                    <div class="mb-3">
                        <label asp-for=Street></label>
                        <input asp-for=Street type="text" class="form-control" placeholder="Prospect Peremohy 3">
                    </div>

                    <div class="col-md-3 mb-3">
                        <label asp-for=PostalCode></label>
                        <input asp-for=PostalCode type="text" class="form-control" placeholder="03072" required>
                        <div class="invalid-feedback">
                            Post code required.
                        </div>
                    </div>

                    <button asp-controller="User" asp-action="AddAddress" class="btn btn-primary btn-lg btn-block" type="submit">Add address</button>
                </div>
            </div>
        </form>

        <footer class="my-5 pt-5 text-muted text-center text-small">
            <p class="mb-1">&copy; 2017-2018 Company Name</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Privacy</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Support</a></li>
            </ul>
        </footer>
    </div>
</body>

MarketPlace/Views/User/ChangeAddress.cshtml
@model Addresses

<body>
    <div class="container">
        <div class="py-5 text-center">
            <img class="d-block mx-auto mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
            <h2>Address form</h2>
        </div>
        <form method="post" asp-action="ChangeAddress">
            <div class="row BtnCenter">
                <div class="col-md-8 order-md-1">
                    <h4 class="mb-3">Billing address</h4>
                    <div class="mb-3">
                        <label asp-for=Country></label>
                        <input asp-for=Country type="text" class="form-control" value="@Model.Country" required>
                        <div class="invalid-feedback">
                            Please enter your country.
                        </div>
                    </div>

                    <div class="mb-3">
                        <label asp-for=City></label>
                        <input asp-for=City type="text" class="form-control" value="@Model.City">
                    </div>

                    <div class="mb-3">
                        <label asp-for=Street></label>
                        <input asp-for=Street type="text" class="form-control" value="@Model.Street">
                    </div>

                    <div class="col-md-3 mb-3">
                        <label asp-for=PostalCode></label>
                        <input asp-for=PostalCode type="text" class="form-control" value="@Model.PostalCode" required>
                        <div class="invalid-feedback">
                            Post code required.
                        </div>
                    </div>

                    <button asp-controller="User" asp-action="ChangeAddress" class="btn btn-primary btn-lg btn-block" type="submit">Change address</button>
                </div>
            </div>
        </form>

        <footer class="my-5 pt-5 text-muted text-center text-small">
            <p class="mb-1">&copy; 2017-2018 Company Name</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Privacy</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Support</a></li>
            </ul>
        </footer>
    </div>
</body>

MarketPlace/Views/User/EditProfile.cshtml
@model ApplicationUsers
<div class="container">
    @if (TempData["Error"] != null)
    {
        <div class="col-md-12 alert-danger">
            <span>@TempData["Error"]</span>
        </div>
    }
    <div class="main-body">
        <div class="row">
            <div class="col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="https://bootdey.com/img/Content/avatar/avatar6.png" alt="Admin" class="rounded-circle p-1 bg-primary" width="110">
                            <div class="mt-3">
                                <h4>@Model.FirstName @Model.LastName</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <form asp-action="EditProfile">
                    <div class="card">
                        <div class="card-body">
                            <div class="row mb-3">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Name</h6>
                                </div>

                                <div class="col-sm-9 text-secondary">
                                    <input asp-for="FirstName" type="text" class="form-control" value="@Model.FirstName">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Last name</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input asp-for=LastName type="text" class="form-control" value="@Model.LastName">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Username</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input asp-for=UserName type="text" class="form-control" value="@Model.UserName">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Email</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input asp-for=Email type="email" class="form-control" value="@Model.Email">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Mobile</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input asp-for=PhoneNumber type="tel" class="form-control" value="@Model.PhoneNumber">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-3"></div>
                                <div class="col-sm-9 text-secondary">
                                    <button asp-controller="User" asp-action="EditProfile" class="btn btn-primary px-4">Save changes</button>
                                    <button asp-controller="User" asp-action="MyProfile" class="btn btn-secondary px-4">Back to profile</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MarketPlace/Views/User/MyProfile.cshtml
@using static MarketPlace.Helpers.Roles;
@model MarketPlace.ViewModels.UserViewModel

<div class="container">
    <label style="font-size:30px;text-align:center;display:block" class="text-danger">@TempData["NoAddress"]</label>
    <label style="font-size:30px;text-align:center;display:block" asp-validation-for="@Model.ApplicationUsers.EmailConfirmed" class="text-danger">@TempData["NotConfirmed"]</label>
    <div class="main-body">
        <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">User Profile</li>
            </ol>
        </nav>
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="https://bootdey.com/img/Content/avatar/avatar7.png" style="border: 2px solid white;" alt="Admin" class="rounded-circle" width="150">
                            <div class="mt-3">
                                <h4>@Model.ApplicationUsers.FirstName @Model.ApplicationUsers.LastName</h4>
                                <h5>Role-@Model.Role</h5>
                                <p class="text-secondary mb-1"></p>
                            </div>
                        </div>
                    </div>
                </div>
                @if (Model.Role != Role.Vendor && Model.Role != Role.Admin)
                {
                    <form asp-action="BecomeVendor">
                        <button asp-action="BecomeVendor" class="mt-2 btn btn-primary" style="width:100%">Become vendor</button>
                    </form>
                }
            </div>
            <div class="col-md-8">
                <div class="card mb-3">

                    <div class="card-body">

                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Full Name</h6>
                            </div>
                            <div class="col-sm-9">
                                @Model.ApplicationUsers.FirstName @Model.ApplicationUsers.LastName
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Email</h6>
                            </div>
                            <div class="col-sm-9">
                                @Model.ApplicationUsers.Email
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Username</h6>
                            </div>
                            <div class="col-sm-9">
                                @Model.ApplicationUsers.UserName
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Mobile</h6>
                            </div>
                            <div class="col-sm-9">
                                @Model.ApplicationUsers.PhoneNumber
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Address</h6>
                            </div>
                            <div class="col-sm-9">
                                @Model.ApplicationUsers.Address?.City, @Model.ApplicationUsers.Address?.Country, @Model.ApplicationUsers.Address?.Street
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-12">
                                <a asp-controller="User" asp-action="EditProfile" class="btn btn-primary px-4">Edit profile</a>
                                @if (Model.ApplicationUsers.AddressId != null)
                                {
                                    <a asp-controller="User" asp-action="ChangeAddress" class="btn btn-primary px-4">Change adress</a>
                                }
                                else
                                {
                                    <a asp-controller="User" asp-action="AddAddress" class="btn btn-primary px-4">Add adress</a>
                                }
                                @if (!Model.ApplicationUsers.EmailConfirmed)
                                {
                                    <a asp-controller="Account" asp-action="SendEmail" class="btn btn-primary" asp-route-id="@Model.ApplicationUsers.Id">Verify account</a>
                                }
                                <a asp-controller="Order" asp-action="ViewOrder" class="btn btn-primary" asp-route-id="@Model.ApplicationUsers.Id">My orders</a>
                                <a asp-controller="Home" asp-action="Index" class="btn btn-secondary px-4">Back to homepage</a>
                                @if (User.IsInRole(Role.Vendor) || User.IsInRole(Role.Admin))
                                {
                                    <div class="mt-2">
                                        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Product controls
                                        </button>
                                        <div class="dropdown-menu">
                                            <a asp-controller="Product" asp-action="AddProduct" class="dropdown-item">Add product</a>
                                            <a asp-controller="Product" asp-action="AddProductExcel" class="dropdown-item">Add products through excel</a>
                                            <a asp-controller="Product" asp-action="AllUserProducts" class="dropdown-item">My products</a>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>